name: Cross-Version

on: [push, pull_request]

jobs:

  test_java:
    name: Java ${{ matrix.java }}
    strategy:
      fail-fast: false
      matrix:
        java: [18, 19, 20]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ matrix.java }}
          version: latest
      - name: Test
        run: >
          ./mvnw -B -e -V --no-transfer-progress
          verify javadoc:javadoc
          -Djapicmp.breakBuildOnBinaryIncompatibleModifications=true
          -Djansi.passthrough=true
          -Dmaven.artifact.threads=100
          -Dmaven.compiler.fork=true
          -DskipTests
          -Dstyle.color=always          

